### ISSUE TITLE
--require-uppercase-charecters Spelling typo

### ISSUE THREAD

**Issue by varunchandak** [DenizParlak/Zeus#1]
**--require-uppercase-charecters** is wrong. It should be **--require-uppercase-characters**

**Comment by DenizParlak** [comment]
Yep, I've forgotten I'm gonna fix it :) Thank you.

**Comment by DenizParlak** [comment]
fixed

**Comment by DenizParlak** [comment]
fixed #33

**Comment by DenizParlak** [comment]
fixed #1
