### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by nealpeters86** [DenizParlak/Zeus#9]
After a clean install on Amazon Linux VM I get the following error:

./zeus.sh: line 884: syntax error near unexpected token `}'

**Comment by varunchandak** [comment]
that's an incomplete if-else-fi block. You need to add **fi** before the curly braces.

Also, you'll get the similar error on line 1152 or something.

**Comment by DenizParlak** [comment]
@varunchandak you're right but there is no any syntax error on line 1152?

@nealpeters86 it's fixed now, thanks.

**Comment by cyberopus** [comment]
Syntax error issue for current zeus.sh:

```
./zeus.sh: line 904: syntax error near unexpected token `}'
./zeus.sh: line 904: `}'
```

**Comment by DenizParlak** [comment]
It's fixed.
